[package]
name = "rocket-eg-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.10"
serde = { version = "1.0.131", features = ["derive"] }
serde_json = "1.0.72"
